import { router } from 'expo-router';
import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AppColors } from '@/constants/app-theme';
import { useCharacterChat } from '@/hooks/use-character-chat';
import { useProgress } from '@/hooks/use-progress';
import { fetchCharacterReply } from '@/services/character-reply';
import type { Character, CharacterMessage } from '@/types/learning';

interface CharacterScreenProps { character: Character; }

export function CharacterScreen({ character }: CharacterScreenProps) {
  const { messages, isHydrated, appendMessage, createMessage, startNewConversation } = useCharacterChat(character);
  const { registerCharacterInteraction } = useProgress();
  const [draft, setDraft] = useState(''); const [sending, setSending] = useState(false);
  const [suggestions, setSuggestions] = useState<readonly string[]>(['Hello!', 'Tell me more.', 'Can you help me?']);
  const scrollRef = useRef<ScrollView>(null);
  const scrollToLatest = useCallback(() => scrollRef.current?.scrollToEnd({ animated: true }), []);
  const send = useCallback(async (raw: string): Promise<void> => { const text = raw.trim(); if (!text || sending || !isHydrated) return; appendMessage(createMessage('user', text)); registerCharacterInteraction(character.id, 'chat'); setDraft(''); setSending(true); try { const reply = await fetchCharacterReply(character.id, text); if (!reply) { appendMessage(createMessage('tutor', 'Oops! Could you try that again?')); return; } appendMessage(createMessage('tutor', reply.text, reply.correction)); setSuggestions(reply.suggestions); } catch (error: unknown) { console.warn('No se pudo responder como personaje.', error); appendMessage(createMessage('tutor', 'Sorry, I lost the signal for a moment. Please try again.')); } finally { setSending(false); } }, [appendMessage, character.id, createMessage, isHydrated, registerCharacterInteraction, sending]);
  return <SafeAreaView style={styles.safeArea} edges={['top','right','bottom','left']}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
    <View style={styles.header}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable><View style={styles.identity}><Text style={styles.avatar}>{character.avatar}</Text><View><Text style={styles.name}>{character.name}</Text><Text style={styles.status}>{character.vocabularyFocus} · {character.difficulty === 'facil' ? 'Fácil' : 'Medio'}</Text></View></View><Pressable onPress={() => router.push(`/call/${character.id}`)}><Text style={styles.call}>Escuchar</Text></Pressable></View>
    {!isHydrated ? <View style={styles.loading}><ActivityIndicator color={AppColors.primaryBright}/><Text style={styles.status}>Cargando charla…</Text></View> : <><ScrollView ref={scrollRef} style={styles.flex} contentContainerStyle={styles.messages} onContentSizeChange={scrollToLatest} keyboardShouldPersistTaps="handled">{messages.map((message) => <Bubble key={message.id} message={message} avatar={character.avatar}/>) }{sending ? <Text style={styles.typing}>{character.name} está escribiendo…</Text> : null}</ScrollView>
      <View style={styles.composer}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{suggestions.map((suggestion) => <Pressable key={suggestion} style={styles.chip} disabled={sending} onPress={() => void send(suggestion)}><Text style={styles.chipText}>{suggestion}</Text></Pressable>)}</ScrollView><View style={styles.inputRow}><TextInput value={draft} onChangeText={setDraft} editable={!sending} placeholder="Escribe en inglés…" placeholderTextColor={AppColors.textMuted} style={styles.input} multiline maxLength={500} onSubmitEditing={() => void send(draft)}/><Pressable style={[styles.send, (!draft.trim() || sending) && styles.disabled]} disabled={!draft.trim() || sending} onPress={() => void send(draft)}><Text style={styles.sendText}>Enviar</Text></Pressable></View><Pressable disabled={sending} onPress={() => { startNewConversation(); setSuggestions(['Hello!', 'Tell me more.', 'Can you help me?']); }}><Text style={styles.newChat}>Nueva conversación</Text></Pressable></View></>}
  </KeyboardAvoidingView></SafeAreaView>;
}
function Bubble({ message, avatar }: { message: CharacterMessage; avatar: string }) { const tutor = message.role === 'tutor'; return <View style={[styles.bubbleRow, tutor ? styles.left : styles.right]}>{tutor ? <Text style={styles.smallAvatar}>{avatar}</Text> : null}<View style={[styles.bubble, tutor ? styles.tutorBubble : styles.userBubble]}><Text selectable style={styles.message}>{message.text}</Text>{message.correction ? <View style={styles.correction}><Text style={styles.correctionTitle}>Oops, I think you meant:</Text><Text style={styles.corrected}>{message.correction.correctedText}</Text><Text style={styles.explanation}>{message.correction.explanation}</Text></View> : null}</View></View>; }
const styles = StyleSheet.create({ safeArea:{flex:1,backgroundColor:AppColors.background},flex:{flex:1},header:{minHeight:68,backgroundColor:AppColors.surface,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},back:{color:AppColors.primaryBright,fontWeight:'800'},identity:{flexDirection:'row',alignItems:'center',gap:7,flex:1,justifyContent:'center'},avatar:{fontSize:28},smallAvatar:{fontSize:25},name:{color:AppColors.text,fontWeight:'800'},status:{color:AppColors.textMuted,fontSize:11},call:{color:AppColors.primaryBright,fontWeight:'800'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:10},messages:{padding:16,gap:12,maxWidth:720,width:'100%',alignSelf:'center'},bubbleRow:{flexDirection:'row',alignItems:'flex-end',gap:7},left:{justifyContent:'flex-start'},right:{justifyContent:'flex-end'},bubble:{maxWidth:'80%',padding:12,borderRadius:18},tutorBubble:{backgroundColor:AppColors.surfaceRaised,borderBottomLeftRadius:4},userBubble:{backgroundColor:AppColors.primary,borderBottomRightRadius:4},message:{color:AppColors.text,lineHeight:22},correction:{borderTopColor:AppColors.textMuted,borderTopWidth:1,marginTop:8,paddingTop:7},correctionTitle:{color:AppColors.primaryBright,fontSize:12,fontWeight:'800'},corrected:{color:AppColors.text,fontWeight:'800',marginTop:3},explanation:{color:AppColors.textMuted,fontSize:12,marginTop:3},typing:{color:AppColors.textMuted,fontStyle:'italic'},composer:{backgroundColor:AppColors.surface,padding:12,gap:9},chips:{gap:8},chip:{borderColor:AppColors.primary,borderWidth:1,borderRadius:999,paddingHorizontal:11,paddingVertical:7},chipText:{color:AppColors.text,fontSize:13},inputRow:{flexDirection:'row',alignItems:'flex-end',gap:8},input:{flex:1,minHeight:46,maxHeight:104,backgroundColor:AppColors.surfaceRaised,borderRadius:14,color:AppColors.text,padding:11},send:{backgroundColor:AppColors.primary,borderRadius:14,padding:14},sendText:{color:AppColors.text,fontWeight:'800'},disabled:{opacity:.5},newChat:{color:AppColors.textMuted,textAlign:'center',fontSize:12,paddingTop:2} });
